"""Statement integrity — cheap tamper/authenticity signals for lending.

None of these prove fraud; they are flags for a human underwriter. The strongest
one we already had for free: a doctored amount breaks the running-balance chain,
so validate.py is itself a tamper check. This module adds two more from data we
already hold — a scanned page spliced into a digital export, and PDF metadata
that names an editing tool rather than a bank's server library.

Deliberately conservative: a statement is called "verified" only when the
balance reconciles AND nothing else is off, and "review" otherwise, each flag a
plain sentence. False positives (a bank statement legitimately re-saved through
a tool) are acceptable because the output is a prompt to look, not an accusation.
"""
from __future__ import annotations

import re
from datetime import datetime

# Server PDF libraries that genuine Indian bank exports are generated by. Their
# presence is reassuring; their absence is not itself a flag (banks change
# tooling, and customers legitimately re-save through utilities).
BANK_GENERATORS = ("itext", "openpdf", "jasperreport", "oracle", "sap",
                   "crystal", "stimulsoft", "birt", "docmosis", "pdfbox")

# Interactive editing / assembly tools. A bank statement is not produced by
# these; seeing one means the file was opened and re-authored.
EDITING_TOOLS = ("pdf-lib", "pdfsharp", "photoshop", "illustrator", "gimp",
                 "canva", "inkscape", "microsoft word", "powerpoint",
                 "libreoffice", "google docs", "foxit phantom", "nitro")


def _pdfdate(s: str):
    """Parse a PDF date string 'D:YYYYMMDDHHmmSS...' to a datetime, or None."""
    m = re.search(r"D:(\d{4})(\d{2})(\d{2})(\d{2})?(\d{2})?(\d{2})?", s or "")
    if not m:
        return None
    y, mo, d, hh, mm, ss = (int(x) if x else 0 for x in m.groups())
    try:
        return datetime(y, mo, d, hh, mm, ss)
    except ValueError:
        return None


def statement_flags(meta) -> list[str]:
    """Authenticity flags for one source statement (excludes balance, which is
    an account-level property)."""
    flags: list[str] = []
    combo = f"{meta.producer} {meta.creator}".lower()

    tool = next((t for t in EDITING_TOOLS if t in combo), None)
    if tool:
        flags.append(f"{meta.source_file}: created with an editing tool "
                     f"({tool}), not a bank's statement generator")

    up = len(getattr(meta, "unreadable_pages", None) or [])
    if up:
        flags.append(f"{meta.source_file}: {up} page(s) have no text layer — a "
                     f"scanned image spliced into a digital export")
    elif not getattr(meta, "is_digital_text", True):
        flags.append(f"{meta.source_file}: no text layer at all (a scan)")

    # NB: a ModDate after CreationDate is deliberately NOT a flag. Genuine
    # statements are routinely re-saved (password removal, re-download), so it
    # false-positives constantly; the producer/creator and scanned-page signals
    # are the reliable ones. The dates are still carried and shown, for a human.
    return flags


def modified_gap_days(meta) -> int | None:
    """How many days after creation the PDF was last modified — informational
    only (shown to the underwriter, never an automatic flag)."""
    created, modified = _pdfdate(meta.pdf_created), _pdfdate(meta.pdf_modified)
    if created and modified:
        return max((modified - created).days, 0)
    return None


def account_integrity(metas: list, balance_status: str) -> dict:
    """Aggregate integrity for one account (its statements + its balance chain).

    assessment is 'verified' only when the chain reconciles and no statement
    raises a flag; otherwise 'review', with every reason listed.
    """
    flags: list[str] = []
    balance_ok = balance_status == "passed"
    if not balance_ok:
        flags.append("the running balance does not reconcile — a doctored amount "
                     "or a missing page will both do this")
    for m in metas:
        flags.extend(statement_flags(m))

    return {
        "assessment": "verified" if (balance_ok and not flags) else "review",
        "balance_verified": balance_ok,
        "flags": flags,
    }
